@startuml
entity User {
    * id: Long
    * name: String
    * email: String
    * password: String
}

entity Task {
    * id: Long
    * title: String
    * description: String
    * dueDate: LocalDate
    * priority: String
    * status: String
    * user_id: Long
}

User ||--o{ Task
@enduml
